### ISSUE TITLE
Linux masternode dependencies

### ISSUE THREAD

**Issue by JeroenDeDauw** [sagacrypto/SagaCoin#1]
I have been trying to follow the Linux guide at https://sagacoin.net/masternode.html

First I tried using https://github.com/sagacrypto/SagaCoin/releases/download/1.0.0.2/sagacoin_1.0.0.2_ubuntu16.04.tar.gz on a fresh Ubuntu 16.04. When running `./sagacoind` I got an error about some libboost files missing. I installed libboost-dev and libboost-1.58-dev, but no dice.

Then I tried the build approach described in https://github.com/sagacrypto/SagaCoin#build-linux-see-the-wiki-for-dependencies, starting with cloning this git repo. Again errors about missing dependencies.

I installed a bunch of things based on what is at the top of the readme:

> SagaCoin uses libsecp256k1, libgmp, Boost1.55, OR Boost1.57,
> Openssl1.01m, Berkeley DB 4.8, QT5 to compile

Still errors. Perhaps I used the wrong packages.

**Is there a list of dependencies that need to be installed on Ubuntu 16.04 (in the form of console commands)? If not, can such a list be provided?**

**Comment by tokayseo** [comment]
I was told this was what they ran to get it to work on their server (Saga Owners).

apt-get install build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev -y

I used that and still not working

**Comment by JeroenDeDauw** [comment]
Worked for me:

```
apt-get update
apt-get install build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev -y
```

**Comment by JeroenDeDauw** [comment]
I just noticed the binary comes with a readme.txt >_>

Contents:

> If you failed to run SagaCoin-qt, then please ensure dependencies are installed, else perform the following commands:-
> sudo apt-get update
> sudo apt-get install build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev -y
> sudo apt-get install libminiupnpc-dev mesa-common-dev libgmp-dev libgl1-mesa-dev -y
> sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 libqt5printsupport5 -y
