### ISSUE TITLE
error: Please implement AtomicPointer for this platform

### ISSUE THREAD

**Issue by IOTAPUNKS** [sagacrypto/SagaCoin#7]
Please help me! Thanks

root@xxxx:~/SagaCoin/src# cd leveldb && make libleveldb.a libmemenv.a
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/builder.cc -o db/builder.o
In file included from ./port/port_posix.h:50:0,
                 from ./port/port.h:14,
                 from ./db/filename.h:14,
                 from db/builder.cc:7:
./port/atomic_pointer.h:212:2: error: #error Please implement AtomicPointer for this platform.
 #error Please implement AtomicPointer for this platform.
Makefile:211: recipe for target 'db/builder.o' failed
make: *** [db/builder.o] Error 1

**Comment by heginbotham1** [comment]
Install libboost AtomicPointer into you packages

**Comment by sagacrypto** [comment]
I don't know what is your platform of "this platform"... But we have implemented ARM64 into our coding, will update the code to public soon. This will allow ARM64 like Raspberry Pi and other single board computer.

**Comment by sagacrypto** [comment]
Added ARM64 support in version 1.2.0.2.
