### ISSUE TITLE
Error: Error loading block database

### ISSUE THREAD

**Issue by nad010286** [sagacrypto/SagaCoin#8]
I start Sagacoin server by ./sagacoind in Sagacoin/src
and have this error.

Please help

**Comment by ghost** [comment]
Me too

**Comment by sagacrypto** [comment]
Maybe you have corrupted blockchain, you may try to delete all blockchain and try again. Or reload block data with bootstrap file at https://github.com/sagacrypto/SagaCoin_Bootstrap.
