### ISSUE TITLE
cant find library

### ISSUE THREAD

**Issue by jdamhost** [sagacrypto/SagaCoin#9]
I am trying to install the sagacoind but when I run the command I get the error 👍 
sagacoind: error while loading shared libraries: libdb_cxx-5.1.so: cannot open shared object file

I have checked and I have both 4.8 and 5.1 installed but cannot resolve the issue is anyone able to point me in the right direction?

**Comment by sagacrypto** [comment]
You should read the readme carefully, you need to install all dependency libraries at https://github.com/sagacrypto/SagaCoin/wiki/Unix-Build
